version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: api_geeco-in_mariadb_1
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=geeco_in_db
      - MYSQL_USER=geeco_user
      - MYSQL_PASSWORD=user_password
    ports:
      - "3306"  # Docker asignará un puerto dinámico
    volumes:
      - db_data:/var/lib/mysql

  api:
    build: .
    container_name: api_geeco-in_fastapi_1
    depends_on:
      - mariadb
    environment:
      - DATABASE_URL=mysql+pymysql://geeco_user:user_password@mariadb/geeco_in_db
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  db_data: